spring:
#  profiles: eureka-server-01
  application:
    name: exchange
  freemarker:
    allow-request-override: false
    cache: false # 开发阶段关闭缓存
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bh_exchange?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    tomcat:
      # 最大空闲连接数量
      max-idle: 50
      # 初始化连接数量
      initial-size: 50
      # 最小空闲连接数量
      min-idle: 20
      # 连接池中最大的活跃连接数
      max-active: 1000
      # 最大等待返回时间
      max-wait: 1000
server:
  port: 8080
mybatis:
  type-aliases-package: com.xr.exchange.model
  mapper-locations: classpath:mapper/*.xml
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

---

spring:
  profiles: exchange
  application:
    name: exchange
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bh_exchange?useUnicode=true&characterEncoding=utf-8
    username:
    password:
    tomcat:
      # 最大空闲连接数量
      max-idle: 50
      # 初始化连接数量
      initial-size: 50
      # 最小空闲连接数量
      min-idle: 20
      # 连接池中最大的活跃连接数
      max-active: 1000
      # 最大等待返回时间
      max-wait: 1000
server:
  port: 80